theme = "awesome-identity"
baseURL = "https://matlads.github.io"
title = "Martin Atukunda"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Martin"
  lastname = "Atukunda"
  title = "Senior Software Engineer"
  bio = """Martin Atukunda brings over 20 years experience in Software Application Development, System and Network Administration, Data Management, Database Administration, and Project Management. This experience comprises all phases and levels of the object oriented applications development from design to delivery, data analysis, software team management, as well as extensive System and Network Administration experience
  """


## Footer Configurations
[params.footer]
  copyright = "© 2023 Martin Atukunda. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
